FROM python:3.10.2

WORKDIR /usr/src/app
RUN pip install Flask
RUN pip install mysql.connector
RUN pip install PyMySQL
RUN pip install Flask-Session

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
